In [ ]:
# 5.2 创建矩阵
# mat函数创建矩阵时，若输入已为matrix或者ndarray对象，则不会为他们创建副本。
# 因此，用mat函数和调用matrix(data, copy=False）等价。

In [2]:
# （1）在创建矩阵的专用字符串中， 矩阵的行与行之间用【分号】隔开，行内的元素之间用【空格】隔开
import numpy as np

A = np.mat('0 2 0; 2 2 0; 0 1 0')
B = np.mat('-1, -1 1; -1 0 1; 1 1 -1')
C = A.dot(B)
D = np.dot(A, B)
print(C == D)
print(A)
print(B)
print(C)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[0 2 0]
 [2 2 0]
 [0 1 0]]
[[-1 -1  1]
 [-1  0  1]
 [ 1  1 -1]]
[[-2  0  2]
 [-4 -2  4]
 [-1  0  1]]
