In [3]:
from numpy import *

# 2.1 NumPy数组对象

a = arange(5)
print(a)
print(a.shape)
print(a.dtype)

[0 1 2 3 4]
(5,)
int32


In [7]:
# 2.2 创建多维数组

m = array([arange(2), arange(2)])
print(m)
print(m.shape)

[[0 1]
 [0 1]]
(2, 2)


In [9]:
# 2.2.1 选取数组元素

print(m[1, 1])

1


In [10]:
# 2.2.4 字符编码（整数、无符号整数、单精度浮点数等）

b = arange(7, dtype='f')
print(b.dtype)

float32


In [14]:
# 2.4 一维数组的索引和切片

# 0到7，步长为2
a = arange(9)
print(a[0:7:2])

# 反转数组
print(a[9:0:-1])

[0 2 4 6]
[8 7 6 5 4 3 2 1]


In [16]:
# 2.5 可以使用省略号(...)来表示遍历剩下的维度。

# 改变维度，一维24个元素转成2组 3*4 的矩阵。
a = arange(24).reshape(2, 3, 4)
print(a)
print(a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
22


In [ ]:
# 选取数据

# 选取一个数据
print(a[1, 2, 2])

# 选取多个数据
print(a[0, :, :])

# 省略号代替

print(a[0, ...])

# 选取前两维也是可以的

print(a[0, 1])

In [ ]:
# 2.9 数组的分割


