In [2]:
from numpy import *

# 2.1 NumPy数组对象

a = arange(5)
print(a)
print(a.shape)
print(a.dtype)

[0 1 2 3 4]
(5,)
int32


In [7]:
# 2.2 创建多维数组

m = array([arange(2), arange(2)])
print(m)
print(m.shape)

[[0 1]
 [0 1]]
(2, 2)


In [9]:
# 2.2.1 选取数组元素

print(m[1, 1])

1


In [10]:
# 2.2.4 字符编码（整数、无符号整数、单精度浮点数等）

b = arange(7, dtype='f')
print(b.dtype)

float32


In [14]:
# 2.4 一维数组的索引和切片

# 0到7，步长为2
a = arange(9)
print(a[0:7:2])

# 反转数组
print(a[9:0:-1])

[0 2 4 6]
[8 7 6 5 4 3 2 1]


In [16]:
# 2.5 可以使用省略号(...)来表示遍历剩下的维度。

# 改变维度，一维24个元素转成2组 3*4 的矩阵。
a = arange(24).reshape(2, 3, 4)
print(a)
print(a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
22


In [ ]:
# 选取数据

# 选取一个数据
print(a[1, 2, 2])

# 选取多个数据
print(a[0, :, :])

# 省略号代替

print(a[0, ...])

# 选取前两维也是可以的

print(a[0, 1])

In [4]:
# 2.6 改变数组的维度
# (1) ravel 完成展平的操作

b = arange(24).reshape(2,3,4)
# print(b)
print(b.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [6]:
# (2) flatten 展平。 flatten函数会请求分配内存来保存结果。而ravel函数只是返回数组的一个视图。

print(b.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [8]:
# (3) 用元组设置维度。除了reshape,还可直接用一个正整数元组来设置数组的维度。

b.shape = (6,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [9]:
# (4) transpose 转置。可以用于多维数组。
print(b.transpose())

[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


In [13]:
# (4) resize 和 reshape() 函数的功能一样，但resize会直接修改所操作的数组。

print(b.resize(2, 12))
print(b)

None
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [15]:
# 数组的组合  
# 乘法计算
a = arange(9).reshape(3,3)
b = a * 2
print(b)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [18]:
# (1) 水平组合。将ndarray对象构成的元组作为参数，传给hstack
print(hstack((a, b)))
print("==========================================================================================================")
# concatenate函数也是一样的效果
print(concatenate((a, b), axis=1))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [21]:
# (2) vstack 垂直组合
print(vstack((a, b)))
print("---------------------------------")
print(concatenate((a,b), axis=0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
---------------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [22]:
# 2.9 数组的分割

a = array([arange(5), arange(5), arange(5), arange(5), arange(5)])
print(a)
print("-----------")
print(a[1:-1, 1:-1])

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
-----------
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [23]:
# 2.11 tolist 函数
print(a.tolist())

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
