In [5]:
# 5.3.3 随机模块（numpy.random）
import numpy as np
import numpy.random as random
# 设置随机种子
random.seed(42)
# 产生1*3 ［0，1）的随机数
a = random.rand(3, 3)
print(type(a))
print(a.shape)

(3, 3)

In [4]:
# 以下四种方式相同，都是制定大小产生［0，1）的随机数
random.random((3, 3))
random.sample((3, 3))
random.random_sample((3, 3))


array([[ 0.43194502,  0.29122914,  0.61185289],
       [ 0.13949386,  0.29214465,  0.36636184],
       [ 0.45606998,  0.78517596,  0.19967378]])

In [8]:
# 产生10个［1，6）之间的浮点随机数
5*random.random(10) + 1
random.uniform(1, 6, 10)

array([ 1.23225206,  4.03772426,  1.85262062,  1.32525796,  5.74442769,
        5.82816017,  5.04198674,  2.52306885,  1.48836057,  4.42116513])

In [10]:
# 产生10个 ［1，6］ 之间的整数随机数
random.randint(1, 6, 10)


array([4, 5, 3, 1, 4, 2, 4, 2, 2, 4])

In [11]:
# 2 * 5 标准正态分布样本
random.normal(size=(2, 5))

array([[ 0.21863832,  0.88176104, -1.00908534, -1.58329421,  0.77370042],
       [-0.53814166, -1.3466781 , -0.88059127, -1.1305523 ,  0.13442888]])

In [12]:
# 产生5个，n = 5, p=0.5 的二项分布样本
random.binomial(n=5, p=0.5, size=5)

array([3, 1, 5, 3, 2])

In [23]:
# 随机采样
a = range(10)
print(a)
random.choice(a, 7)



range(0, 10)


array([8, 4, 5, 3, 9, 6, 8])

In [18]:
# 对a 乱序 并返回一个新的arr
b = random.permutation(a)
print(b)

[7 1 3 9 8 5 6 4 2 0]


In [29]:
# 对a 乱序 in-place
print(a)
sh = list(a)
random.shuffle(sh)
print(sh)


range(0, 10)
[2, 8, 4, 1, 6, 3, 0, 9, 5, 7]


In [27]:
print(list(range(1, 9)))

[1, 2, 3, 4, 5, 6, 7, 8]
